<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rehan" failures="1" tests="3" name="Create Patient and verify patient is created " time="22.635" errors="0" timestamp="2023-03-03T17:26:35 IST">
  <testcase classname="chl.CreatePatient" name="login" time="8.289"/>
  <testcase classname="chl.CreatePatient" name="createPatient" time="8.187">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Same email id did not expect [Email ID already exist.] but found [Email ID already exist.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Same email id did not expect [Email ID already exist.] but found [Email ID already exist.]
at chl.CreatePatient.createPatient(CreatePatient.java:142)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createPatient -->
  <testcase classname="chl.CreatePatient" name="patientList" time="5.157"/>
</testsuite> <!-- Create Patient and verify patient is created  -->
